prometheus:
  enabled: true
  prometheusSpec:
    replicas: 2 # (ou mais, conforme necessidade)
    tolerations:
    - key: "kubernetes.azure.com/scalesetpriority"
      operator: "Equal"
      value: "spot"
      effect: "NoSchedule"
    


alertmanager:
  enabled: true
  alertmanagerSpec:
    replicas: 2 # (ou mais, conforme necessidade)
    tolerations:
    - key: "kubernetes.azure.com/scalesetpriority"
      operator: "Equal"
      value: "spot"
      effect: "NoSchedule"

grafana:
  grafanaSpec:
    tolerations:
    - key: "kubernetes.azure.com/scalesetpriority"
      operator: "Equal"
      value: "spot"
      effect: "NoSchedule"
      topologyKey: "kubernetes.io/hostname"