prometheus:
  prometheusSpec:
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: "kubernetes.azure.com/scalesetpriority"
              operator: In
              values:
              - "spot"
            - key: "nodepool-type"
              operator: In
              values:
              - "user"
            - key: "workload-type"
              operator: In
              values:
              - "general"
            - key: "environment"
              operator: In
              values:
              - "hub"
    tolerations:
    - key: "kubernetes.azure.com/scalesetpriority"
      operator: "Equal"
      value: "spot"
      effect: "NoSchedule"
    podAntiAffinity: "hard"  # Use "hard" em vez de um objeto

alertmanager:
  alertmanagerSpec:
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: "kubernetes.azure.com/scalesetpriority"
              operator: In
              values:
              - "spot"
            - key: "nodepool-type"
              operator: In
              values:
              - "user"
            - key: "workload-type"
              operator: In
              values:
              - "general"
            - key: "environment"
              operator: In
              values:
              - "hub"
    tolerations:
    - key: "kubernetes.azure.com/scalesetpriority"
      operator: "Equal"
      value: "spot"
      effect: "NoSchedule"
    podAntiAffinity: "hard"  # Use "hard" em vez de um objeto