
# ---
# eck-elasticsearch:
#   enabled: true

# eck-kibana:
#   enabled: true
#   # This is also adjusting the kibana reference to the elasticsearch resource named previously so that
#   # both the eck-elasticsearch and the eck-kibana chart work together by default in the eck-stack chart.
#   elasticsearchRef:
#     name: elasticsearch

# # If enabled, will use the eck-agent chart and deploy an Elastic Agent instance.
# #
# eck-agent:
#   enabled: true

# # If enabled, will use the eck-fleet-server chart and deploy a Fleet Server resource.
# #
# eck-fleet-server:
#   enabled: false

# # If enabled, will use the eck-beats chart and deploy a Beats resource.
# #
# eck-beats:
#   enabled: false

# # If enabled, will use the eck-logstash chart and deploy a Logstash resource.
# #
# eck-logstash:
#   enabled: false

# # If enabled, will use the eck-apm-server chart and deploy a standalone APM Server resource.
# #
# eck-apm-server:
#   enabled: true

# # If enabled, will use the eck-enterprise-search chart and deploy a Enterprise Search resource.
# #
# eck-enterprise-search:
#   enabled: false