controller:
  replicas: 1 # Additional replicas will cause sharding of managed clusters across number of replicas.
  metrics:
    enabled: true
    service:
      annotations:
        prometheus.io/scrape: true
  env:
    - name: ARGOCD_K8S_CLIENT_QPS #required for Crossplane too many CRDs https://github.com/argoproj/argo-cd/pull/448
      value: '300'

tolerations:
- key: CriticalAddonsOnly
  operator: Equal
  value: "true"
  effect: NoSchedule
nodeSelector:
  nodepool-type: system

repoServer:
  autoscaling:
    enabled: true
    minReplicas: 1
  resources: # Adjust based on your specific use case (required for HPA)
    requests:
      cpu: '100m'
      memory: '256Mi'
    limits:
      cpu: '200m'
      memory: '512Mi'
  metrics:
    enabled: true
    service:
      annotations:
        prometheus.io/scrape: true

applicationSet:
  replicaCount: 1 # The controller doesn't scale horizontally, is active-standby replicas
  metrics:
    enabled: true
    service:
      annotations:
        prometheus.io/scrape: true

server:
  autoscaling:
    enabled: true
    minReplicas: 1
  resources: # Adjust based on your specific use case (required for HPA)
    requests:
      cpu: '100m'
      memory: '256Mi'
    limits:
      cpu: '200m'
      memory: '512Mi'
  metrics:
    enabled: true
    service:
      annotations:
        prometheus.io/scrape: true
  ingress:
    enabled: true
    ingressClassName: nginx-internal
    annotations:
      kubernetes.azure.com/tls-cert-keyvault-uri: https://kvmdause2hub.vault.azure.net/certificates/star-brmania-com-br
      kubernetes.azure.com/use-webhook-admission: "true"
      service.beta.kubernetes.io/azure-load-balancer-internal: 'true'
      nginx.ingress.kubernetes.io/rewrite-target: /$1
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      nginx.ingress.kubernetes.io/proxy-body-size: 64m
      nginx.ingress.kubernetes.io/proxy-read-timeout: "7300"
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
      nginx.ingress.kubernetes.io/use-regex: "true"
    hostname: argo.brmania.com.br
    path: /
    pathType: Prefix
    tls: true
    extraTls:
      - hosts:
          - argo.brmania.com.br
        secretName: keyvault-argocd-internal-ingress

configs:
  cm:
    application.resourceTrackingMethod: 'annotation' #use annotation for tracking required for Crossplane
    resource.exclusions: |
      - kinds:
        - ProviderConfigUsage
        apiGroups:
        - "*"

# -- Array of extra K8s manifests to deploy
## Note: Supports use of custom Helm templates
##       It gets handle in this form inside the argo-cd chart
# {{ range .Values.extraObjects }}
# ---
# {{ if typeIs "string" . }}
#     {{- tpl . $ }}
# {{- else }}
#     {{- tpl (toYaml .) $ }}
# {{- end }}
# {{ end }}
extraObjects:
  - |
    apiVersion: argoproj.io/v1alpha1
    kind: AppProject
    metadata:
      name: default
      namespace: {{ $.Release.Namespace | quote }}
      annotations:
        source: gitops-brigde
    spec:
      clusterResourceWhitelist:
      - group: '*'
        kind: '*'
      sourceRepos:
        - '*'
      destinations:
        - namespace: '*'
          name: '*'
          server: '*'
